#!/usr/bin/env bash

set -e

# =================================================================================================

_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -z ${ECR_DOMAIN+x} ]; then
    ECR_DOMAIN=707906211298.dkr.ecr.us-east-2.amazonaws.com
fi

_MEDIATOR_IMAGE=indicio-tech/aries-mediator
_MEDIATOR_IMAGE_FQ=$ECR_DOMAIN/$_MEDIATOR_IMAGE


# =================================================================================================


require_env() {
    if [ -z ${IMAGE_VER+x} ]; then
        echo "The IMAGE_VER environment variable is not set."
        echo
        exit 1
    fi

    if [ -z ${DEPLOYMENT_ENV+x} ]; then
        echo "The DEPLOYMENT_ENV environment variable is not set."
        echo
        exit 1
    fi
}


require_env_full() {
    require_env

    if [ -z ${HTTP_PORT+x} ]; then
        echo "The HTTP_PORT environment variable is not set."
        echo
        exit 1
    fi

    if [ -z ${WS_PORT+x} ]; then
        echo "The WS_PORT environment variable is not set."
        echo
        exit 1
    fi

    if [ -z ${HTTP_ENDPOINT+x} ]; then
        echo "The HTTP_ENDPOINT environment variable is not set."
        echo
        exit 1
    fi

    if [ -z ${WS_ENDPOINT+x} ]; then
        echo "The WS_ENDPOINT environment variable is not set."
        echo
        exit 1
    fi

    if [ -z ${AGENT_NAME+x} ]; then
        echo "The AGENT_NAME environment variable is not set."
        echo
        exit 1
    fi
}


mediator_build() {
    require_env

    pushd $_DIR/mediator/app

    docker build --no-cache -t $_MEDIATOR_IMAGE .
    docker tag $_MEDIATOR_IMAGE:latest $_MEDIATOR_IMAGE_FQ:latest
    docker tag $_MEDIATOR_IMAGE:latest $_MEDIATOR_IMAGE_FQ:$IMAGE_VER
}


mediator_bootstrap() {
    require_env_full

    pushd $_DIR/mediator/app

    if [[ "$1" != INVITE_ONLY ]]; then
        docker build --no-cache -t $_MEDIATOR_IMAGE:bootstrap .
    fi

    docker run -it \
        -v $_DIR/mediator/app/etc/indy:/etc/indy \
        -e DEPLOYMENT_ENV=$DEPLOYMENT_ENV \
        -e HTTP_PORT=$HTTP_PORT \
        -e WS_PORT=$WS_PORT \
        -e HTTP_ENDPOINT=$HTTP_ENDPOINT \
        -e WS_ENDPOINT=$WS_ENDPOINT \
        -e AGENT_NAME=$AGENT_NAME \
        $_MEDIATOR_IMAGE:bootstrap ./provision
}


mediator_push() {
    require_env

    docker push $_MEDIATOR_IMAGE_FQ:latest
    docker push $_MEDIATOR_IMAGE_FQ:$IMAGE_VER
}


# =================================================================================================


display_usage() {
    echo "Deployment helper for Indicio Infrastructure"
    echo
    echo "Usage:"
    echo
    echo "  deploy mediator COMMAND"
    echo
    echo "Commands:"
    echo
    echo "  build"
    echo "  push"
    echo "  bootstrap"
    echo "  invite"
    echo
}

if [[ $# -lt 2 ]]; then
    display_usage
    exit 1
fi

if [[ "$1" != "mediator" ]]; then
    display_usage
    exit 1
fi

if [[ "$2" == "bootstrap" ]]; then
    if [[ "$3" == "--invite-only" ]]; then
        mediator_bootstrap INVITE_ONLY
    else
        mediator_bootstrap
    fi

    exit 0
fi


if [[ "$2" == "build" ]]; then
    mediator_build
    exit 0
fi

if [[ "$2" == "push" ]]; then
    mediator_push
    exit 0
fi

display_usage
exit 1
