FROM dbluhm/aries-cloudagent:405715d1

RUN pip3 install --no-cache-dir git+https://github.com/hyperledger/aries-acapy-plugin-toolbox@v0.1.0

USER root
# Waiting for endpoint
ADD ./tunnel-wait.sh tunnel-wait.sh
RUN chmod +x tunnel-wait.sh
ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 ./jq
RUN chmod +x ./jq
USER $user

COPY ./configs configs/

ENTRYPOINT ["/bin/bash", "-c", "./tunnel-wait.sh \"$@\"", "--"]
CMD ["aca-py", "start", "--arg-file", "./configs/local.yml"]
