#!/bin/bash

export MSYS_NO_PATHCONV=1
# getDockerHost; for details refer to https://github.com/bcgov/DITP-DevOps/tree/main/code/snippets#getdockerhost
. /dev/stdin <<<"$(cat <(curl -s --raw https://raw.githubusercontent.com/bcgov/DITP-DevOps/main/code/snippets/getDockerHost))"
set -e

SCRIPT_HOME="$(cd "$(dirname "$0")" && pwd)"

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage() {
  cat <<-EOF
      Usage: $0 [command] [options]
      Commands:
      build       - Build the mediator docker images
      start | up  - Run mediator
                    You can run "$0 --logs" to tail the docker log files interactively
                    Run "$2 --controller" to start a sample controller (vs setting "--auto" mode in the agent)
                    You can run "$0 --tunnel" to to use tunnel instead of ngrok
      logs        - To tail the logs of running containers (ctrl-c to exit).
      stop | down - Stop mediator
      rm          - Stop mediator and remove volumes
EOF
  exit 1
}

toLower() {
  echo $(echo ${@} | tr '[:upper:]' '[:lower:]')
}

exportEnvironment() {
  for arg in "$@"; do
    case "$arg" in
      *=*)
        export "${arg}"
        ;;
      --controller)
        USE_CONTROLLER=1
        ;;
      --tunnel)
        USE_TUNNEL=1
        ;;
      --logs)
        TAIL_LOGS=1
        ;;
      *)
        # If not recognized, save it for later procesing ...
        set -- "$@" "$arg"
        ;;
    esac
  done

  export LOG_LEVEL=${LOG_LEVEL:-INFO}
  export MEDIATOR_AGENT_HTTP_IN_PORT=3000
  export MEDIATOR_AGENT_WS_IN_PORT=3001


  if [ -z "${PWD_HOST_FQDN}" ]; then
      export DOCKERHOST=$(getDockerHost)
      export ENV=local
      export MEDIATOR_ENDPOINT_URL=http://${DOCKERHOST}:${MEDIATOR_AGENT_HTTP_IN_PORT}
      if  [ ! -z "${USE_TUNNEL}" ]; then
          export ENV=local_tunnel
      fi
  else
      PWD_HOST="${PWD_HOST_FQDN}"
      if [ "$PWD_HOST_FQDN" = "labs.play-with-docker.com" ]; then
        export ETH_CONFIG="eth1"
      elif [ "$PWD_HOST_FQDN" = "play-with-docker.vonx.io" ]; then
        export ETH_CONFIG="eth0"
      else
        export ETH_CONFIG="eth0"
      fi
      MY_HOST=`ifconfig ${ETH_CONFIG} | grep inet | cut -d':' -f2 | cut -d' ' -f1 | sed 's/\./\-/g'`
      export DOCKERHOST="ip${MY_HOST}-${SESSION_ID}-${MEDIATOR_AGENT_HTTP_IN_PORT}.direct.${PWD_HOST_FQDN}"
      export ENV=pwd
      export MEDIATOR_ENDPOINT_URL=http://$DOCKERHOST
  fi

  export MEDIATOR_AGENT_HTTP_ADMIN_PORT=3002
  export MEDIATOR_WALLET_NAME=${MEDIATOR_WALLET_NAME:-mediator}
  export MEDIATOR_WALLET_KEY=${MEDIATOR_WALLET_KEY:-testing}
  export MEDIATOR_AGENT_ADMIN_URL="http://mediator:${MEDIATOR_AGENT_HTTP_ADMIN_PORT}"

  export MEDIATOR_AGENT_LABEL=Mediator
  export MEDIATOR_AGENT_ADMIN_API_KEY="7gdmVBiJalMj52Oum50yD8neu/nxmv3/DTWcZPyKZ4K2UdNNwSPKgg=="
  export MEDIATOR_AGENT_ADMIN_MODE="admin-insecure-mode"
  if [ ! -z "${MEDIATOR_AGENT_ADMIN_API_KEY}" ]; then
    MEDIATOR_AGENT_ADMIN_MODE="admin-api-key ${MEDIATOR_AGENT_ADMIN_API_KEY}"
  fi
  export MEDIATOR_CONTROLLER_PORT=${MEDIATOR_CONTROLLER_PORT:-3010}
  if [ ! -z "${USE_CONTROLLER}" ]; then
    # controller will respond to connection requests
    export MEDIATOR_ARG_FILE=./configs/mediator.yml
    export DEMO_CONTROLLER=mediator-controller
    export MEDIATOR_CONTROLLER_URL="http://${DEMO_CONTROLLER}:${MEDIATOR_CONTROLLER_PORT}"
    export MEDIATOR_CONTROLLER_ADMIN_API_KEY="7gdmVBiJalMj52Oum50yD8neu/nxmv3/DTWcZPyKZ4K2UdNNwSPKgg=="
    #export MEDIATOR_CONTROLLER_WEBHOOK="--webhook-url ${MEDIATOR_CONTROLLER_URL}/webhooks#${MEDIATOR_CONTROLLER_ADMIN_API_KEY}"
    export MEDIATOR_CONTROLLER_WEBHOOK="--webhook-url ${MEDIATOR_CONTROLLER_URL}/webhooks"
    export MEDIATOR_ALIAS="Controller"
  else
    # agent is started in "--auto" mode
    export MEDIATOR_ARG_FILE=./configs/mediator-auto-accept.yml
    export DEMO_CONTROLLER=
    export MEDIATOR_CONTROLLER_URL=
    export MEDIATOR_CONTROLLER_ADMIN_API_KEY=
    export MEDIATOR_CONTROLLER_WEBHOOK=
    export MEDIATOR_ALIAS=
  fi

  export POSTGRESQL_HOST=db
  export POSTGRESQL_PORT=5432
  export POSTGRESQL_USER=postgres
  export POSTGRESQL_PASSWORD=development
  export POSTGRESQL_DATABASE=postgres
  export POSTGRESQL_ADMIN_USER=postgres
  export POSTGRESQL_ADMIN_PASSWORD=development

}

function logs() {
  (
    local OPTIND
    local unset _force
    local unset no_tail
    while getopts ":f-:" FLAG; do
      case $FLAG in
        f ) local _force=1 ;;
        - )
            case ${OPTARG} in
                "no-tail"*) no_tail=1
              ;;
            esac
      esac
    done
    shift $((OPTIND-1))

    log_args=()
    (( no_tail != 1 )) && log_args+=( '-f' )
    if [ ! -z "${TAIL_LOGS}" ] || [ ! -z "${_force}" ]; then
      docker-compose \
        --log-level ERROR logs \
         "${log_args[@]}" "$@"
    fi
  )
}

# =================================================================================================================

pushd ${SCRIPT_HOME} >/dev/null
COMMAND=$(toLower ${1})
shift || COMMAND=usage

case "${COMMAND}" in
build)
  exportEnvironment "$@"
  if [ "$ENV" = "local" ]; then
      docker-compose build ngrok ngrok_ws mediator db ${DEMO_CONTROLLER}
  elif [ "$ENV" = "local_tunnel" ]; then
      docker-compose build tunnel tunnel_ws mediator db ${DEMO_CONTROLLER}
  else
      docker-compose build mediator db ${DEMO_CONTROLLER}
  fi
  ;;
start|up)
  exportEnvironment "$@"
  if [ "$ENV" = "local" ]; then
      docker-compose up -d ngrok ngrok_ws mediator db ${DEMO_CONTROLLER}
  elif [ "$ENV" = "local_tunnel" ]; then
      docker-compose up -d tunnel tunnel_ws mediator db ${DEMO_CONTROLLER}
  else
      docker-compose up -d mediator db ${DEMO_CONTROLLER}
  fi
  logs
  echo "Run './manage logs' for logs"
  ;;
logs)
  exportEnvironment "$@"
  docker-compose logs -f
  ;;
stop|down)
  exportEnvironment "$@"
  docker-compose stop
  ;;
down|rm)
  exportEnvironment "$@"
  docker-compose down
  ;;
*)
  usage
  ;;
esac

popd >/dev/null
