FROM mediator_pq_acapy

ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 /usr/bin/jq
RUN chmod +x /usr/bin/jq

COPY ./start.sh start.sh
COPY ./configs configs


RUN chmod +x start.sh && \
  aca-py --version > ./acapy-version.txt

ENTRYPOINT ["bash", "./start.sh"]